// backend/src/controllers/posts.js
const prisma = require("../utils/prisma");
const { uploadToSupabase } = require("../services/storage");

/* ------------------------------------------------------------
   Helpers
------------------------------------------------------------ */
function formatPlaytime(seconds = 0) {
  const totalMinutes = Math.floor(seconds / 60);
  if (totalMinutes <= 0) return "меньше часа в системе";

  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;

  if (hours && minutes) return `${hours} ч ${minutes} мин в системе`;
  if (hours) return `${hours} ч в системе`;
  return `${minutes} мин в системе`;
}

function humanLang(code = "") {
  switch (code.toLowerCase()) {
    case "uk": return "украинский";
    case "ru": return "русский";
    case "en": return "английский";
    case "ja": return "японский";
    case "de": return "немецкий";
    default: return `язык: ${code || "неизвестный"}`;
  }
}

function generateDynamicBio(stats) {
  if (!stats) return "Autogenerated field operator.";
  return `
Стаж оператора: ${formatPlaytime(stats.total_playtime)}.
Локация: ${stats.country || "неустановленной страны"}${stats.city ? ", " + stats.city : ""}.
Системный язык: ${humanLang(stats.system_lang)}.
${stats.safe_mode ? "SAFE-режим включён." : "SAFE-режим отключён."}
  `.trim();
}

/* ------------------------------------------------------------
   GET /posts
------------------------------------------------------------ */
async function listPosts(_req, res) {
  try {
    const posts = await prisma.post.findMany({
      orderBy: { createdAt: "desc" },
      include: { images: true, fakeAuthor: true }
    });

    const withViews = await Promise.all(
      posts.map(async (p) => {
        const count = await prisma.view.count({ where: { postId: p.id } });
        return { ...p, viewsCount: count, author: p.fakeAuthor };
      })
    );

    res.json(withViews);
  } catch (err) {
    console.error("❌ listPosts error:", err);
    res.status(500).json({ error: "Failed to load posts" });
  }
}

/* ------------------------------------------------------------
   GET /posts/:id
------------------------------------------------------------ */
async function getPost(req, res) {
  try {
    const postId = Number(req.params.id);
    if (!postId) return res.status(400).json({ error: "Invalid post ID" });

    const post = await prisma.post.findUnique({
      where: { id: postId },
      include: { images: true, fakeAuthor: true }
    });

    if (!post) return res.status(404).json({ error: "Post not found" });

    const viewsCount = await prisma.view.count({ where: { postId } });

    const user = req.user;

    // анонимный
    if (!user) return res.json({ ...post, author: post.fakeAuthor, viewsCount });

    // admin
    if (user.type === "system" && user.role === "ADMIN")
      return res.json({ ...post, author: post.fakeAuthor, viewsCount });

    // real user → подмена автора
    if (user.type === "real") {
      const real = user.realUser;
      const systemUserId = real.userId;

      if (post.fakeAuthor?.userId === systemUserId) {
        const stats = await prisma.gameProfile.findFirst({
          where: { playerId: real.password },
          orderBy: { collected_at: "desc" }
        });

        const substituted = {
          ...post.fakeAuthor,
          codename: real.username,
          avatarUrl: real.avatarUrl || post.fakeAuthor.avatarUrl,
          rank: "Operator",
          clearance: "D-13",
          bio: stats ? generateDynamicBio(stats) : "Autogenerated field operator."
        };

        return res.json({
          ...post,
          author: substituted,
          fakeAuthor: substituted,
          viewsCount
        });
      }
    }

    return res.json({ ...post, author: post.fakeAuthor, viewsCount });

  } catch (err) {
    console.error("❌ getPost error:", err);
    res.status(500).json({ error: "Failed to load post" });
  }
}

/* ------------------------------------------------------------
   GET /posts/archive
------------------------------------------------------------ */
async function listArchive(_req, res) {
  try {
    const posts = await prisma.post.findMany({
      where: { NOT: { coverImage: null } },
      orderBy: { createdAt: "desc" },
      include: { fakeAuthor: true }
    });

    res.json(posts.map((p) => ({ ...p, author: p.fakeAuthor })));
  } catch (err) {
    console.error("❌ listArchive error:", err);
    res.status(500).json({ error: "Failed to load archive" });
  }
}

/* ------------------------------------------------------------
   POST /posts  (ADMIN)
------------------------------------------------------------ */
async function createPost(req, res) {
  try {
    if (req.user.role !== "ADMIN")
      return res.status(403).json({ error: "Admin only" });

    const { title, body, coverCaption, stamp, clearance, fakeAuthorId } = req.body;
    if (!title || !body)
      return res.status(400).json({ error: "title and body required" });

    let coverImage = null;
    let fileType = null;

    // 🔥 правильная загрузка файла → Supabase
    if (req.file) {
      const safeName = `${Date.now()}-${req.file.originalname.replace(/[^\w.-]/g, "_")}`;
      coverImage = await uploadToSupabase(req.file.path, safeName, req.file.mimetype);
      fileType = req.file.mimetype;
    }

    const created = await prisma.post.create({
      data: {
        title,
        body,
        coverImage,
        coverCaption: coverCaption || null,
        stamp: stamp || null,
        clearance: clearance || null,
        fakeAuthorId: fakeAuthorId ? Number(fakeAuthorId) : null,
        fileType
      },
      include: { fakeAuthor: true }
    });

    res.status(201).json({ ...created, author: created.fakeAuthor });

  } catch (err) {
    console.error("❌ createPost error:", err);
    res.status(500).json({ error: "Failed to create post" });
  }
}

/* ------------------------------------------------------------
   PUT /posts/:id  (ADMIN)
------------------------------------------------------------ */
async function updatePost(req, res) {
  try {
    if (req.user.role !== "ADMIN")
      return res.status(403).json({ error: "Admin only" });

    const id = Number(req.params.id);
    const exists = await prisma.post.findUnique({ where: { id } });
    if (!exists) return res.status(404).json({ error: "Post not found" });

    const { title, body, coverCaption, stamp, clearance, fakeAuthorId } = req.body;

    let coverImage = exists.coverImage;

    // 🔥 если загружен новый файл → перезаливаем
    if (req.file) {
      const safeName = `${Date.now()}-${req.file.originalname.replace(/[^\w.-]/g, "_")}`;
      coverImage = await uploadToSupabase(req.file.path, safeName, req.file.mimetype);
    }

    const updated = await prisma.post.update({
      where: { id },
      data: {
        title,
        body,
        coverImage,
        coverCaption,
        stamp,
        clearance,
        fakeAuthorId: fakeAuthorId ? Number(fakeAuthorId) : exists.fakeAuthorId
      },
      include: { fakeAuthor: true }
    });

    res.json({ ...updated, author: updated.fakeAuthor });

  } catch (err) {
    console.error("❌ updatePost error:", err);
    res.status(500).json({ error: "Failed to update post" });
  }
}

/* ------------------------------------------------------------
   POST /posts/:id/view
------------------------------------------------------------ */
async function addView(req, res) {
  try {
    const id = Number(req.params.id);
    const { sessionId } = req.body;

    if (!id || !sessionId)
      return res.status(400).json({ error: "Missing post ID or sessionId" });

    await prisma.view.create({
      data: { postId: id, sessionId }
    });

    res.json({ message: "View recorded" });
  } catch (err) {
    console.error("❌ addView error:", err);
    res.status(500).json({ error: "Failed to record view" });
  }
}

module.exports = {
  listPosts,
  getPost,
  listArchive,
  addView,
  createPost,
  updatePost,
  deletePost
};
