// backend/src/routes/fakeusers.js
const express = require("express");
const router = express.Router();
const prisma = require("../utils/prisma");
const { authRequired } = require("../middleware/auth");
const controller = require("../controllers/fakeUserController");

// =======================
// Helpers
// =======================
async function getLatestStatsForRealUser(real) {
  if (!real || !real.password) return null;

  return prisma.gameProfile.findFirst({
    where: { playerId: real.password }, // UUID из Ren'Py
    orderBy: { collected_at: "desc" },
  });
}

function formatPlaytime(seconds = 0) {
  const minutes = Math.floor(seconds / 60);
  if (minutes < 1) return "меньше часа в системе";

  const h = Math.floor(minutes / 60);
  const m = minutes % 60;

  if (h && m) return `${h} ч ${m} мин в системе`;
  if (h) return `${h} ч в системе`;
  return `${m} мин в системе`;
}

function humanLang(code = "") {
  switch ((code || "").toLowerCase()) {
    case "uk": return "украинский";
    case "ru": return "русский";
    case "en": return "английский";
    case "ja": return "японский";
    case "de": return "немецкий";
    default: return `язык: ${code || "неизвестный"}`;
  }
}

function generateDynamicBio(stats) {
  if (!stats) return "Autogenerated field operator.";

  return `
Стаж оператора: ${formatPlaytime(stats.total_playtime)}.
Локация: ${stats.country || "неустановленной страны"}${stats.city ? ", " + stats.city : ""}.
Системный язык: ${humanLang(stats.system_lang)}.
${stats.safe_mode ? "SAFE-режим включён." : "SAFE-режим отключён."}
  `.trim();
}

// ===========================================================
// 🔐 Все ниже — только авторизованные
// ===========================================================
router.use(authRequired);

/* =======================================================
   📌 Получить ВСЕХ исследователей
   ======================================================= */
router.get("/", async (req, res) => {
  console.log("FAKEUSERS: req.user =", req.user);
  try {
    const u = req.user; // то что кладёт authRequired

    const fakeUsers = await prisma.fakeUser.findMany({
      orderBy: { id: "asc" },
      include: { user: true },
    });

    // ✅ Админ — видит всех как есть
    if (u.role === "ADMIN" && !u.realUserId) {
      return res.json(fakeUsers);
    }

    // ✅ Если это RealUser-логин → берём конкретного real по realUserId
    if (u.realUserId) {
      const real = await prisma.realUser.findUnique({
        where: { id: u.realUserId },
      });

      if (!real) return res.json(fakeUsers);

      const stats = await getLatestStatsForRealUser(real);

      const result = fakeUsers.map((fu) => {
        // подменяем ТОЛЬКО слот, привязанный к system user игрока
        if (fu.userId !== real.userId) return fu;

        return {
          ...fu,
          codename: real.username,
          avatarUrl: real.avatarUrl || fu.avatarUrl,
          rank: "Operator",
          clearance: "D-13",
          bio: generateDynamicBio(stats),
        };
      });

      return res.json(result);
    }

    // ✅ Системный не-админ (если вдруг есть) — просто как есть
    return res.json(fakeUsers);
  } catch (err) {
    console.error("FakeUsers error:", err);
    return res.status(500).json({ error: "Failed to load fake users" });
  }
});

/* =======================================================
   📌 Получить ОДНОГО исследователя
   ======================================================= */
router.get("/:id", async (req, res) => {
  console.log("FAKEUSER SINGLE: req.user =", req.user);
  try {
    const id = Number(req.params.id);
    const u = req.user;

    let fu = await prisma.fakeUser.findUnique({
      where: { id },
      include: {
        user: true,
        posts: { orderBy: { createdAt: "desc" } },
      },
    });

    if (!fu) return res.status(404).json({ error: "Researcher not found" });

    // ✅ Админ — без подмен
    if (u.role === "ADMIN" && !u.realUserId) {
      return res.json(fu);
    }

    // ✅ Реальный игрок — подменяем, если это его слот
    if (u.realUserId) {
      const real = await prisma.realUser.findUnique({
        where: { id: u.realUserId },
      });

      if (real && fu.userId === real.userId) {
        const stats = await getLatestStatsForRealUser(real);

        fu = {
          ...fu,
          codename: real.username,
          avatarUrl: real.avatarUrl || fu.avatarUrl,
          rank: "Operator",
          clearance: "D-13",
          bio: generateDynamicBio(stats),
        };
      }
    }

    return res.json(fu);
  } catch (err) {
    console.error("FakeUser profile error:", err);
    return res.status(500).json({ error: "Failed to load researcher" });
  }
});

/* =======================================================
   📌 Посты исследователя
   ======================================================= */
router.get("/:id/posts", async (req, res) => {
  try {
    const id = Number(req.params.id);
    const u = req.user;

    const fu = await prisma.fakeUser.findUnique({
      where: { id },
      include: { user: true },
    });
    if (!fu) return res.status(404).json({ error: "Researcher not found" });

    let posts = await prisma.post.findMany({
      where: { fakeAuthorId: fu.id },
      orderBy: { createdAt: "desc" },
      include: { fakeAuthor: true },
    });

    // ✅ Админ — без подмен
    if (u.role === "ADMIN" && !u.realUserId) {
      return res.json({ posts });
    }

    // ✅ Реальный игрок — подмена автора, если это его слот
    if (u.realUserId) {
      const real = await prisma.realUser.findUnique({
        where: { id: u.realUserId },
      });

      if (real && fu.userId === real.userId) {
        const stats = await getLatestStatsForRealUser(real);

        posts = posts.map((p) => ({
          ...p,
          fakeAuthor: {
            ...p.fakeAuthor,
            codename: real.username,
            avatarUrl: real.avatarUrl || p.fakeAuthor.avatarUrl,
            rank: "Operator",
            clearance: "D-13",
            bio: generateDynamicBio(stats),
          },
        }));
      }
    }

    return res.json({ posts });
  } catch (err) {
    console.error("FakeUser posts error:", err);
    return res.status(500).json({ error: "Failed to load posts" });
  }
});

router.post(
  "/",
  controller.upload.single("avatar"),
  controller.createFakeUser
);

// 🔥 UPDATE NPC
router.put(
  "/:id",
  controller.upload.single("avatar"),
  controller.updateFakeUser
);

// 🔥 DELETE NPC
router.delete("/:id", controller.deleteFakeUser);

module.exports = router;
